name: Build and test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: actions/checkout@v3
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
        run: ./gradlew clean build --no-daemon
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: lib/build/reports/jacoco/test/jacocoTestReport.csv
